[theme]
primaryColor="#007acc"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false